import * as z from "zod"
import { StripeInvoiceStatus } from "@prisma/client"

export const StripeInvoiceZod = z.object({
  id: z.string(),
  userId: z.string(),
  dealId: z.string(),
  stripePaymentId: z.string(),
  amount: z.number().int(),
  exSystemIncome: z.number().int(),
  exReflectedAmount: z.number().int(),
  exRefundedAmount: z.number().int(),
  status: z.nativeEnum(StripeInvoiceStatus),
  capturedAt: z.date().nullish(),
  reflectedAt: z.date().nullish(),
  releasedAt: z.date().nullish(),
  refundedAt: z.date().nullish(),
  stripePaymentIntentId: z.string(),
  customerPaymentFee: z.number().int(),
  customerTransactionFee: z.number().int(),
  sellerTransactionFee: z.number().int(),
  sellerCancelFee: z.number().int(),
  stripeRefundUid: z.string().nullish(),
  stripeIntentUid: z.string().nullish(),
  stripeCaptured: z.boolean(),
  stripeRefunded: z.boolean(),
  stripePaid: z.boolean(),
  isValid: z.boolean(),
  insuranceFee: z.number().int(),
  usedPoints: z.number().int(),
  acquiredPoints: z.number().int(),
  syncedAt: z.date().nullish(),
  totalTicketPrice: z.number().int(),
  isDisputed: z.boolean(),
  riskScore: z.number().int(),
  is3dsUsed: z.boolean(),
  createdAt: z.date(),
  updatedAt: z.date(),
})
