name: e2e

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline --immutable
      - run: yarn run tsc
      - run: yarn run lint

  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: ticketx_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --prefer-offline --immutable

      - name: Run prisma migrate
        run: yarn api:db:migrate
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/ticketx_test

      - name: Run prisma seed
        run: yarn api:db:seed
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/ticketx_test

      - name: Build apps
        run: yarn build
        env:
          NODE_ENV: test

      - name: Start api server
        run: |
          yarn workspace api start &
          npx wait-port http://:4000/.well-known/apollo/server-health -t 60000
        env:
          NODE_ENV: test
          DATABASE_URL: postgres://postgres:password@localhost:5432/ticketx_test
          JWT_SECRET: 3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R

      - name: Start web server
        run: |
          yarn workspace web start &
          npx wait-port http://:3000/ -t 60000

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: e2e
          wait-on-timeout: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Cypress E2E Videos
          path: e2e/cypress/videos
